#! /usr/bin/python

import socket
import signal
import threading


signal.signal(signal.SIGINT, signal.SIG_DFL)
c=socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.getprotobyname("udp"))
s=socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.getprotobyname("tcp"))
s.bind(("", 8001))
c.connect(("192.168.3.1", 29301))
s.listen(1)	
while True:
	(v,client)=s.accept()
	data=v.recv(1024)
	print "VENT -  From :",client," Recv: ", data
	c.send(data)
	data=c.recv(1024)
	v.send(data)
	v.close()


