#! /usr/bin/python

import socket
import signal
import threading


signal.signal(signal.SIGINT, signal.SIG_DFL)
tunnel=socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.getprotobyname("udp"))
server=socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.getprotobyname("tcp"))
server.bind(("", 8001))
tunnel.connect(("192.168.3.1", 29301))
server.listen(1)	
while True:
	(client,addr)=server.accept()
	data=client.recv(1024)
	print "VENT -  From :",addr," Recv: ", data
	tunnel.send(data)
	data=tunnel.recv(1024)
	client.send(data)
	client.close()


